import Head from "next/head";
import Image from "next/image";
import { HomeIcon, MenuIcon } from "../Icons";
import Link from "next/link";
import imageLoader from "../../utils/imgLoader";

interface IHeader {
  currentRoute: string;
  onClickMenu: () => void;
}
const Header: React.FC<IHeader> = ({ currentRoute, onClickMenu }) => {
  return (
    <>
      <Head>
        <title>Tu Minh Hieu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="https://raw.githubusercontent.com/kanetu/portfolio/main/public/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="https://raw.githubusercontent.com/kanetu/portfolio/main/public/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://raw.githubusercontent.com/kanetu/portfolio/main/public/favicon/favicon-16x16.png"
        />
        <link
          rel="manifest"
          href="https://raw.githubusercontent.com/kanetu/portfolio/main/public/favicon/site.webmanifest"
        />
        <link
          rel="mask-icon"
          href="https://raw.githubusercontent.com/kanetu/portfolio/main/public/favicon/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <link
          rel="icon"
          type="image/png"
          href="https://raw.githubusercontent.com/kanetu/portfolio/main/public/favicon/favicon.ico"
        />
      </Head>

      <div>
        <Image
          loader={imageLoader}
          src="wall-paper.jpg"
          layout="responsive"
          width="100"
          height="100"
          className="max-h-[15em] object-cover"
          objectFit="contain"
          alt="wall-paper"
        />
        <Image
          loader={imageLoader}
          src="avatar.jpg"
          width="165"
          height="165"
          className="w-[10.3125em] h-[10.3125em] md:w-[14.375em] md:h-[14.375em] rounded-full absolute left-1/2 md:left-[calc(50%-15em)] transform -translate-x-1/2 -translate-y-1/2 md:-translate-y-2/3 border-[white] border-4"
          objectFit="cover"
          alt="avatar"
        />
        <div className="hidden md:block md:relative md:w-full md:h-[2em]">
          <ul className="text-[1.25em] flex justify-between md:max-w-[25em] md:absolute left-[calc(50%-6em)] top-[1.25em] transform -translate-x-1/2 md:-translate-x-0 -translate-y-1/2">
            <li
              className={`${
                currentRoute == "/"
                  ? "border-b-2 border-dashed border-project-primary"
                  : ""
              } md:mx-[1em] md:my-[1em]`}
            >
              <Link href="/">Home</Link>
            </li>
            <li
              className={`${
                currentRoute == "/about"
                  ? "border-b-2 border-dashed border-project-primary"
                  : ""
              } md:mx-[1em] md:my-[1em]`}
            >
              <Link href="/about">About</Link>
            </li>
            <li
              className={`${
                currentRoute == "/works"
                  ? "border-b-2 border-dashed border-project-primary"
                  : ""
              } md:mx-[1em] md:my-[1em]`}
            >
              <Link href="/works">Works</Link>
            </li>
            <li
              className={`${
                currentRoute == "/contact"
                  ? "border-b-2 border-dashed border-project-primary"
                  : ""
              } md:mx-[1em] md:my-[1em]`}
            >
              <Link href="/contact">Contact</Link>
            </li>
            <li
              className={`${
                currentRoute == "/blog"
                  ? "border-b-2 border-dashed border-project-primary"
                  : ""
              } md:mx-[1em] md:my-[1em]`}
            >
              Blog
            </li>
          </ul>
        </div>
        <div className="flex p-[1.5625em] justify-between md:hidden">
          <Link href="/">
            <button className="rounded-full w-[3.125em] h-[3.125em] rounded-full flex items-center justify-center shadow-project">
              <HomeIcon className="w-[1.875em] h-[1.875em]" />
            </button>
          </Link>
          <button
            onClick={onClickMenu}
            className="rounded-full w-[3.125em] h-[3.125em] rounded-full flex items-center justify-center shadow-project"
          >
            <MenuIcon className="w-[1.875em] h-[1.875em]" />
          </button>
        </div>
      </div>
    </>
  );
};

export default Header;
