import Head from "next/head";
import Image from "next/image";
import { HomeIcon, MenuIcon } from "../Icons";
import Link from "next/link";

export default function Header() {
  return (
    <>
      <Head>
        <title>Tu Minh Hieu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Image
          src="/wall-paper.jpg"
          layout="responsive"
          width="100"
          height="100"
          className="max-h-[240px]"
          objectFit="contain"
          alt="wall-paper"
        />
        <Image
          src="/avatar.jpg"
          width="165"
          height="165"
          className="w-[165px] h-[165px] rounded-full absolute left-1/2 transform -translate-x-1/2 -translate-y-1/2 border-[white] border-4"
          objectFit="cover"
          alt="avatar"
        />
        <div className="flex p-[25px] justify-between">
          <Link href="/">
            <button className="rounded-full w-[50px] h-[50px] rounded-full flex items-center justify-center shadow-project">
              <HomeIcon className="w-[30px] h-[30px]" />
            </button>
          </Link>
          <button className="rounded-full w-[50px] h-[50px] rounded-full flex items-center justify-center shadow-project">
            <MenuIcon className="w-[30px] h-[30px]" />
          </button>
        </div>
      </div>
    </>
  );
}
